dist: trusty
sudo: false
language: java

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: script
  script: mvn clean compile package

services:
  - docker

stages:
  - build
  - name: push
    if: fork = false

before_install:
  - docker login -u="$QUAY_USER" -p="$QUAY_PASS" quay.io
  - docker login -u="$RH_REGISTRY_USER" -p="$RH_REGISTRY_PASS" registry.redhat.io

jobs:
  include:
  - stage: build
    script:
    - mvn clean compile package
  - stage: push
    script:
    - docker build -t emergencyresponsedemo/responder-service:$TRAVIS_COMMIT .
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker tag emergencyresponsedemo/responder-service:$TRAVIS_COMMIT quay.io/emergencyresponsedemo/responder-service:$TAG
    - docker push quay.io/emergencyresponsedemo/responder-service:$TAG
